<?php

/**
 * @file
 * Contains paragraphs_table.module.
 */

use Drupal\Component\Utility\Crypt;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Render\Markup;
use Drupal\Core\Site\Settings;
use Drupal\Core\Url;
use Drupal\paragraphs_table\Form\ParagraphCloneForm;
use Drupal\paragraphs_table\Form\ParagraphDeleteForm;
use Drupal\paragraphs_table\Form\ParagraphEditForm;
use Drupal\views\Views;

/**
 * Hide field label.
 */
function _paragraphs_table_hidden_label(&$field_form) {
  $label = '';
  if (!empty($field_form['#title_display'])) {
    $label = $field_form['#title'] ?? '';
    $field_form['#title_display'] = 'invisible';
  }
  if (empty($label) && !empty($field_form['target_id']['#title'])) {
    $label = $field_form['target_id']['#title'];
  }
  // Remove title field date.
  if (!empty($field_form['#type'])) {
    $invisibleType = ['select', 'managed_file', 'entity_autocomplete'];
    if (in_array($field_form['#type'], $invisibleType)) {
      $field_form['#title_display'] = 'invisible';
    }
    if ($field_form['#type'] == 'datetime') {
      $label = $field_form['#title'] ?? '';
      $field_form['#title'] = '';
    }
    if (in_array($field_form['#type'], ['radios', 'checkboxes'])) {
      return $label;
    }
  }
  // Remove fieldset field date & time.
  if (!empty($field_form["#theme_wrappers"][0]) && in_array($field_form["#theme_wrappers"][0], ['fieldset'])) {
    array_shift($field_form["#theme_wrappers"]);
  }
  foreach (Element::children($field_form) as $child) {
    $label = _paragraphs_table_hidden_label($field_form[$child]);
  }
  return $label;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function paragraphs_table_preprocess_field_multiple_value_form(&$variables) {
  $element = $variables['element'];
  if (empty($element['#paragraphsTable'])) {
    return FALSE;
  }
  if (!empty($variables['table'])) {
    // Case number of values unlimited - cardinality = -1.
    if (!empty($element['#paragraphsTable']) && !empty($variables["table"]["#tabledrag"])) {
      if ($element["#paragraphsTable"]["#show_all"] && $element["#cardinality"] > 1) {
        // We don't need the button add more anymore.
        foreach (Element::children($variables["button"]) as $child) {
          if (substr($child, 0, 16) === "add_more_button_") {
            $variables["button"][$child]["#access"] = FALSE;
            break;
          }
        }
        $variables["button"]['#access'] = FALSE;
      }
      if (!$element["#paragraphsTable"]["#table_vertical"]) {
        // Add caption header.
        if (!empty($element["#title"])) {
          $variables["table"]["#caption"] = $variables["element"]["#title"];
          $variables["table"]["#attributes"]["class"][] = 'caption-top';
        }
        if (!empty($element["#title_display"]) && $element["#title_display"] == 'invisible') {
          unset($variables["table"]["#caption"]);
        }

        $row_weight = end($variables["table"]["#header"]);
        if ($element["#cardinality"] == 1) {
          $row_weight = FALSE;
          unset($variables['table']['#tabledrag']);
        }
        if ($element["#cardinality"] < 2) {
          $element["#paragraphsTable"]["#show_all"] = FALSE;
        }
        $is_new = isset($variables['table']['#rows']) && count($variables['table']['#rows']) == 0;
        $variables["table"]["#header"] = _paragraphs_table_header($element["#paragraphsTable"]["#fields"] ?? [], $element["#paragraphsTable"]["#show_all"], $row_weight, $is_new);
        $remove_row = FALSE;
        foreach ($variables["table"]["#rows"] as $delta => $rows) {
          $row = _paragraphs_table_row($element["#paragraphsTable"]["#fields"] ?? [], $rows['data'], $element["#paragraphsTable"]["#show_all"]);
          if (!empty($row)) {
            $variables["table"]["#rows"][$delta]['data'] = $row;
          }
          else {
            $remove_row = TRUE;
            unset($variables["table"]["#rows"][$delta]);
          }
        }
        if ($remove_row) {
          $variables["table"]["#rows"] = array_merge($variables["table"]["#rows"]);
        }
        if (empty($variables["table"]["#rows"]) || !empty($element["#no_header"])) {
          unset($variables["table"]["#header"]);
          unset($variables["table"]["#caption"]);
        }
        elseif ($element["#paragraphsTable"]["#paste_clipboard"]) {
          $colAction = count($variables["table"]["#header"]) - 3;
          // phpcs:ignore
          $icon = '<span class="paste-paragraphs-clipboard bi bi-clipboard-check" role="button" data-table="' . $variables["table"]["#attributes"]["id"] . '" href="#' . $variables["table"]["#attributes"]["id"] . '" data-bs-toggle="tooltip" data-bs-title="' . t('Paste from excel') . '"><i class="d-none">📋</i></span>';
          $variables['table']['#attached']['library'][] = 'paragraphs_table/paste-clipboard';
          if (!empty($element["#paragraphsTable"]["#field_reference"])) {
            $field_reference = $element["#paragraphsTable"]["#field_reference"];
            $fields = $element["#paragraphsTable"]["#fields"];
            $fieldConfig = $fields[$field_reference]->getSettings();
            $entity_type = $fieldConfig["target_type"];
            $columns = [
              ['field' => "state", 'checkbox' => "true"],
            ];
            if ($fieldConfig["handler"] == 'views') {
              $view_name = $fieldConfig["handler_settings"]["view"]["view_name"];
              $display_name = $fieldConfig["handler_settings"]["view"]["display_name"];
              $view = Views::getView($view_name);
              $view->setDisplay($fieldConfig["handler_settings"]["view"]["display_name"]);
              $displayHandler = $view->displayHandlers->get($display_name);
              $fields = $displayHandler->getOption('fields');
              $listType = [
                'list_default',
                'options_select',
                'list_key',
                'options_buttons',
                'list_key',
              ];
              foreach ($fields as $fieldId => $field) {
                $type = $field["type"];
                $typeSearch = in_array($type, $listType) ? 'select' : 'input';
                $columns[] = [
                  'field' => $fieldId,
                  'title' => !empty($field['label']) ? $field['label'] : $field["entity_field"],
                  'sortable' => "true",
                  'filter-control' => $typeSearch,
                ];
              }
            }
            else {
              $columns[] = [
                'field' => 'name',
                'title' => $fields[$field_reference]?->getLabel() ?? '',
                'sortable' => "true",
              ];
            }
            $selection_settings = $fieldConfig["handler_settings"] ?? [];
            if (!empty($selection_settings)) {
              $selection_settings['match_operator'] = $selection_settings['match_operator'] ?? 'CONTAINS';
              $selection_settings['match_limit'] = isset($selection_settings['match_limit']) ? (int) $selection_settings['match_limit'] : 10;
              // Don't serialize entity, it'll be added explicitly afterwards.
              if (isset($selection_settings['entity']) && ($selection_settings['entity'] instanceof EntityInterface)) {
                unset($selection_settings['entity']);
              }
            }
            $data = serialize($selection_settings) . $entity_type . $fieldConfig["handler"];
            $selection_settings_key = Crypt::hmacBase64($data, Settings::getHashSalt());
            $key_value_storage = \Drupal::keyValue('entity_autocomplete');
            if (!$key_value_storage->has($selection_settings_key)) {
              $key_value_storage->set($selection_settings_key, $selection_settings);
            }
            $url = Url::fromRoute('paragraphs_table.field_reference', [
              'target_type' => $entity_type,
              'selection_handler' => $fieldConfig["handler"],
              'selection_settings_key' => $selection_settings_key,
            ])->toString();
            $variables['table']['#attached']['library'][] = 'paragraphs_table/search-reference';
            $variables['table']['#attached']['library'][] = 'paragraphs_table/bootstrapTable';
            $variables['table']['#attached']['drupalSettings']['paragraphs_field_reference'][$field_reference]['columns'] = $columns;
            // phpcs:ignore
            $icon .= '<span class="paragraphs-table-search ms-2 bi bi-search" role="button" data-field_reference_url="' . $url . '" data-table="' . $variables["table"]["#attributes"]["id"] . '" data-field_reference="' . $field_reference . '" data-field="#' . $variables["table"]["#attributes"]["id"] . '" data-bs-toggle="tooltip" data-bs-title="' . t('Search') . '"><i class="d-none">🔍</i></span>';
          }
          $variables["table"]["#header"][$colAction]['data'] = Markup::create($icon);
        }
      }
      else {
        // Table vertical.
        foreach ($variables["table"]["#rows"] as $delta => $rows) {
          if (!empty($element["#paragraphsTable"]["#widget_state"]["paragraphs"][$delta]["mode"]) &&
            $element["#paragraphsTable"]["#widget_state"]["paragraphs"][$delta]["mode"] == 'remove') {
            continue;
          }
          if (!empty($rows["data"][1]["data"]["subform"])) {
            $row = _paragraphs_table_vertical($element["#paragraphsTable"]["#fields"], $rows["data"][1]["data"]["subform"], $delta);
            $variables["table"]["#rows"][$delta]["data"][1]["data"] = $row;
            if (empty($element["#paragraphsTable"]["#show_all"]) && !empty($rows["data"][1]["data"]["top"]["actions"])) {
              $actions = $rows["data"][1]["data"]["top"]["actions"];
              if (!empty($actions["actions"]["collapse_button"])) {
                unset($actions["actions"]["collapse_button"]);
              }
              $variables["table"]["#rows"][$delta]["data"][3]["data"] = $actions;
            }
          }
          else {
            unset($variables["table"]["#rows"][$delta]);
          }
        }
        if (empty($element["#paragraphsTable"]["#show_all"])) {
          $variables["table"]["#header"][] = [
            'data' => '',
            'class' => ['action'],
          ];
        }
      }
    }
  }
  elseif (!empty($element["#cardinality"]) && $element["#cardinality"] == 1) {
    // Case single value.
    if (!$element["#paragraphsTable"]["#table_vertical"]) {
      $variables["elements"][0]["subform"] = _paragraphs_table_1_row($element["#paragraphsTable"]["#fields"], $variables["elements"][0]["subform"]);
      $variables["elements"][0]["subform"]["#header"] = _paragraphs_table_header($element["#paragraphsTable"]["#fields"], TRUE);
    }
    else {
      // Table vertical.
      $variables["elements"][0]["subform"] = _paragraphs_table_vertical($element["#paragraphsTable"]["#fields"], $variables["elements"][0]["subform"]);
    }
  }

  // Add theme-specific libraries to compatible with common admin themes.
  $currentTheme = \Drupal::service('theme.manager')->getActiveTheme()->getName();
  if ($currentTheme === 'gin') {
    $variables['#attached']['library'][] = 'paragraphs_table/ginSupport';
    $variables['table']['#attributes']['class'] = [];
  }

}

/**
 * Get table header.
 */
function _paragraphs_table_header($fields, $show_all = FALSE, $rowWeightCol = FALSE, $is_new = FALSE) {
  $header = ['data' => '', 1 => 'remove'];
  // It will remove later in paragraphs module.
  if (!empty($fields)) {
    foreach ($fields as $field_name => $field) {
      $header[] = [
        'data' => $field->getLabel(),
        'class' => [$field_name],
      ];
    }
  }
  if (!$is_new) {
    $header[] = ['data' => '', 'class' => ['action']];
  }
  else {
    $header[0] = $header[1];
  }
  return $header;
}

/**
 * Get table row.
 */
function _paragraphs_table_1_row($fields, $rows_data, $show_all = FALSE) {
  $rows['#type'] = 'table';
  foreach ($fields as $field_name => $field) {
    $field_form = $rows_data[$field_name];
    _paragraphs_table_hidden_label($field_form['widget']);
    $rows[0][$field_name] = $field_form;
  }
  return $rows;
}

/**
 * Generate table row.
 */
function _paragraphs_table_row($fields, $rows_data, $show_all = FALSE) {
  $row[] = $rows_data[0];
  if (isset($rows_data[1]["data"]["#access"]) &&
    $rows_data[1]["data"]["#access"] === FALSE) {
    return FALSE;
  }
  if (!empty($rows_data[1]["data"]["subform"]) && !empty($rows_data[1]['data']['#paragraph_type'])) {
    $subform = $rows_data[1]["data"]["subform"];
  }
  else {
    return FALSE;
  }
  if (!empty($fields)) {
    foreach ($fields as $field_name => $field) {
      if (!empty($subform[$field_name])) {
        $field_form = $subform[$field_name];
        if (!empty($field_form['widget'])) {
          _paragraphs_table_hidden_label($field_form['widget']);
        }
        $multiple = !empty($field_form["widget"]["#cardinality"]) && $field_form["widget"]["#cardinality"] == -1 ? ' item_paragraphs_table_multiple' : '';
        $row[$field_name] = [
          'data' => $field_form,
          'class' => $field_name . $multiple,
        ];
        unset($subform[$field_name]);
      }
    }
  }
  $actions = !empty($rows_data[1]["data"]["top"]["actions"]) ? $rows_data[1]["data"]["top"]["actions"] : '';
  if (!empty($actions["actions"]["collapse_button"])) {
    unset($actions["actions"]["collapse_button"]);
  }
  $row[] = [
    'data' => $actions,
    'class' => ['action'],
  ];
  // Add weight.
  $row[] = end($rows_data);
  return $row;
}

/**
 * Make subform table vertical.
 */
function _paragraphs_table_vertical($fields, $rows_data, $delta = 0) {
  $subform = ["#type" => 'table'];
  $row_index = 0;
  foreach ($fields as $field_name => $field) {
    $subform[$row_index]['_name'] = [
      '#markup' => $field->getLabel(),
    ];
    $field_form = $rows_data[$field_name];
    if (!empty($field_form['widget'])) {
      _paragraphs_table_hidden_label($field_form['widget']);
    }
    $subform[$row_index++][$field_name] = $field_form;
  }
  return $subform;
}

/**
 * Implements hook_entity_type_build().
 */
function paragraphs_table_entity_type_build(array &$entity_types) {
  $entity_types['paragraph']->setFormClass('entity_edit', ParagraphEditForm::class);
  $entity_types['paragraph']->setFormClass('entity_clone', ParagraphCloneForm::class);
  $entity_types['paragraph']->setFormClass('entity_delete', ParagraphDeleteForm::class);
}

/**
 * Implements hook_theme().
 */
function paragraphs_table_theme($existing, $type, $theme, $path) {
  $variables = [
    'paragraphs_table_chart' => [
      'variables' => [
        'id_field_name' => 'paragraphs-table-chart',
        'settings' => NULL,
      ],
      'template' => 'paragraphs-table-chart',
    ],
  ];

  return $variables;
}

/**
 * Implements hook_entity_type_alter().
 */
function paragraphs_table_type_alter(array &$entity_types) {
  $entity_types['paragraph']->setLinkTemplate('delete-form', '/paragraphs_item/{paragraph}/delete');
}
